### ISSUE TITLE
py2ri not defined 

### ISSUE THREAD

**Issue by mbaddoo** [shwhalen/pyg#1]
Greetings-

I am trying to use pyg with HiCUP test data and am met with the following error:

$ /Applications/ngs/hiC/pyg-master/pyg.py config.json 
/Users/mothership/miniconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
parsing reads pre-mapped to restriction fragments
binning fragment reads
filtering self-ligations
ensuring consistent bin ordering
aggregate reads into counts
creating bin names to simplify grouping/filtering
removing same-bin interactions
computing absolute coverage
/Applications/ngs/hiC/pyg-master/pyg.py:96: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  pd.concat([bin1_coverage, bin2_coverage], axis = 1)
computing relative coverage
merging relative coverage
computing correction factor
computing probability of loci randomly interacting based on relative coverage
computing expected counts
computing significance of interactions using binomial test
parameter chunk: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 112.45it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Applications/ngs/hiC/pyg-master/pyg.py", line 20, in get_pvalues
    for count, probability in parameters
  File "/Applications/ngs/hiC/pyg-master/pyg.py", line 20, in <listcomp>
    for count, probability in parameters
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 102, in __call__
    new_args = [conversion.py2ri(a) for a in args]
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 102, in <listcomp>
    new_args = [conversion.py2ri(a) for a in args]
  File "/Users/mothership/miniconda3/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/rpy2/robjects/conversion.py", line 60, in _py2ri
    raise NotImplementedError("Conversion 'py2ri' not defined for objects of type '%s'" % str(type(obj)))
NotImplementedError: Conversion 'py2ri' not defined for objects of type '<class 'numpy.int64'>'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/ngs/hiC/pyg-master/pyg.py", line 166, in <module>
    for _ in tqdm(parameter_chunks, 'parameter chunk')
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/mothership/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Users/mothership/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
NotImplementedError: Conversion 'py2ri' not defined for objects of type '<class 'numpy.int64'>'

Might you have any ideas on a fix?  I appreciate any assistance you could offer. 

Best-
mbaddoo

**Comment by mbaddoo** [comment]
Greetings,
Just wondering if you can take a look at the issue I opened, please?  I still can't figure out a remedy.
Thanks in advance-
mbaddoo
